USE [master]
GO

/****** Object:  Database [CURSO]    Script Date: 01/04/2020 06:33:41 p. m. ******/
CREATE DATABASE [CURSO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CURSO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS2017\MSSQL\DATA\CURSO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CURSO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS2017\MSSQL\DATA\CURSO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO



/****** Object:  Table [dbo].[REGISTRO]    Script Date: 01/04/2020 06:34:23 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REGISTRO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDOS] [varchar](50) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[EDAD] [int] NOT NULL,
 CONSTRAINT [PK_REGISTRO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

